// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneToManyDemo.Data;

#nullable disable

namespace OneToManyDemo.Migrations
{
    [DbContext(typeof(BoekenDBContext))]
    partial class BoekenDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OneToManyDemo.Models.Auteur", b =>
                {
                    b.Property<int>("AuteurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuteurId"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuteurId");

                    b.ToTable("Auteurs");

                    b.HasData(
                        new
                        {
                            AuteurId = 1,
                            Naam = "Isabel Allende"
                        },
                        new
                        {
                            AuteurId = 2,
                            Naam = "Stephen King"
                        },
                        new
                        {
                            AuteurId = 3,
                            Naam = "J.K. Rowling"
                        },
                        new
                        {
                            AuteurId = 4,
                            Naam = "G.Garcia Marquez"
                        });
                });

            modelBuilder.Entity("OneToManyDemo.Models.Boek", b =>
                {
                    b.Property<int>("BoekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoekId"));

                    b.Property<int>("AuteurId")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoekId");

                    b.HasIndex("AuteurId");

                    b.ToTable("Boeks");

                    b.HasData(
                        new
                        {
                            BoekId = 1,
                            AuteurId = 1,
                            Titel = "Eva Luna"
                        },
                        new
                        {
                            BoekId = 2,
                            AuteurId = 1,
                            Titel = "La casa de los Espiritus"
                        },
                        new
                        {
                            BoekId = 3,
                            AuteurId = 2,
                            Titel = "Horror book"
                        },
                        new
                        {
                            BoekId = 4,
                            AuteurId = 3,
                            Titel = "Harry Potter 1"
                        },
                        new
                        {
                            BoekId = 5,
                            AuteurId = 4,
                            Titel = "Goragora"
                        },
                        new
                        {
                            BoekId = 6,
                            AuteurId = 2,
                            Titel = "Horror book2"
                        },
                        new
                        {
                            BoekId = 7,
                            AuteurId = 3,
                            Titel = "Harry Potter and friends"
                        },
                        new
                        {
                            BoekId = 8,
                            AuteurId = 3,
                            Titel = "Harry Potter and enemies"
                        });
                });

            modelBuilder.Entity("OneToManyDemo.Models.Boek", b =>
                {
                    b.HasOne("OneToManyDemo.Models.Auteur", "Auteur")
                        .WithMany("Boeken")
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Auteur");
                });

            modelBuilder.Entity("OneToManyDemo.Models.Auteur", b =>
                {
                    b.Navigation("Boeken");
                });
#pragma warning restore 612, 618
        }
    }
}
